/* =========================================================================
   COGNITIVE ITEM BANK — original items across 5 classic cognitive domains
   -------------------------------------------------------------------------
   Domains (the ability types measured by mainstream cognitive batteries):
     verbal    — verbal reasoning (analogies, vocabulary, odd-one-out)
     numerical — numerical reasoning (series, word problems, percentages)
     logical   — abstract/logical reasoning (patterns, syllogisms, matrices)
     spatial   — spatial/visual reasoning (rotation, folding, 3-D)
     memory    — working memory & attention (mental manipulation, counting)

   Item shape:
   { id, domain, difficulty: 1|2|3, text{en,vi}, options: [4 × string or
     {en,vi}], answer: <index 0-3>, explain{en,vi} }
   - RIGHT/WRONG scoring (unlike the Likert apps): scoring.js awards the
     item's difficulty weight for a correct answer.
   - 8 items per domain (2 easy, 3 medium, 3 hard) = 40 items (Full).
   - `core: true` marks items 01/03/05/07 of each domain → 20-item Quick
     subset (1 easy, 2 medium, 1 hard per domain — keep this mix if edited).
   - Language-sensitive items (vocabulary) use parallel — not literal —
     translations so both languages test the same skill.
   - Items quoting a letter-string to scan (me02) keep the quoted string in
     English in both languages; the instruction is translated.

   ID prefixes: vr verbal · nu numerical · lg logical · sa spatial · me memory
========================================================================= */

const IQ_QUESTIONS = [
  // ---- VERBAL REASONING ---------------------------------------------------
  { id: "vr01", domain: "verbal", difficulty: 1,
    text: { en: "Bird is to sky as fish is to ___", vi: "Chim so với bầu trời cũng như cá so với ___" },
    options: [{ en: "water", vi: "nước" }, { en: "tree", vi: "cây" }, { en: "sand", vi: "cát" }, { en: "air", vi: "không khí" }],
    answer: 0,
    explain: { en: "A bird moves through the sky; a fish moves through water.", vi: "Chim di chuyển trong bầu trời; cá di chuyển trong nước." } },
  { id: "vr02", domain: "verbal", difficulty: 1,
    text: { en: "Which word does NOT belong: apple, banana, carrot, mango?", vi: "Từ nào KHÔNG cùng nhóm: táo, chuối, cà rốt, xoài?" },
    options: [{ en: "apple", vi: "táo" }, { en: "banana", vi: "chuối" }, { en: "carrot", vi: "cà rốt" }, { en: "mango", vi: "xoài" }],
    answer: 2,
    explain: { en: "Carrot is a vegetable; the others are fruits.", vi: "Cà rốt là rau củ; những từ còn lại là trái cây." } },
  { id: "vr03", domain: "verbal", difficulty: 2,
    text: { en: "Book is to chapter as building is to ___", vi: "Cuốn sách so với chương cũng như tòa nhà so với ___" },
    options: [{ en: "brick", vi: "viên gạch" }, { en: "floor", vi: "tầng" }, { en: "door", vi: "cánh cửa" }, { en: "roof", vi: "mái nhà" }],
    answer: 1,
    explain: { en: "A chapter is a main division of a book, as a floor (storey) is a main division of a building — a brick is material, not a division.", vi: "Chương là một phần chia chính của cuốn sách, cũng như tầng là phần chia chính của tòa nhà — viên gạch là vật liệu, không phải phần chia." } },
  { id: "vr04", domain: "verbal", difficulty: 2,
    text: { en: "Scarce is to abundant as timid is to ___", vi: "Khan hiếm so với dồi dào cũng như rụt rè so với ___" },
    options: [{ en: "shy", vi: "nhút nhát" }, { en: "fearful", vi: "sợ hãi" }, { en: "bold", vi: "bạo dạn" }, { en: "quiet", vi: "trầm lặng" }],
    answer: 2,
    explain: { en: "The pair are opposites: scarce ↔ abundant, so timid ↔ bold.", vi: "Cặp từ là trái nghĩa: khan hiếm ↔ dồi dào, nên rụt rè ↔ bạo dạn." } },
  { id: "vr05", domain: "verbal", difficulty: 2,
    text: { en: "Which word does NOT belong: whisper, murmur, mumble, shout?", vi: "Từ nào KHÔNG cùng nhóm: thì thầm, rì rầm, lẩm bẩm, hét lớn?" },
    options: [{ en: "whisper", vi: "thì thầm" }, { en: "murmur", vi: "rì rầm" }, { en: "mumble", vi: "lẩm bẩm" }, { en: "shout", vi: "hét lớn" }],
    answer: 3,
    explain: { en: "The first three are quiet ways of speaking; shouting is loud.", vi: "Ba từ đầu là cách nói khẽ; hét lớn là nói to." } },
  { id: "vr06", domain: "verbal", difficulty: 3,
    text: { en: "'Ephemeral' most nearly means:", vi: "Từ 'phù du' gần nghĩa nhất với:" },
    options: [{ en: "eternal", vi: "vĩnh cửu" }, { en: "short-lived", vi: "ngắn ngủi" }, { en: "beautiful", vi: "xinh đẹp" }, { en: "fragile", vi: "mong manh" }],
    answer: 1,
    explain: { en: "Ephemeral means lasting a very short time.", vi: "Phù du nghĩa là chỉ tồn tại trong thời gian rất ngắn." } },
  { id: "vr07", domain: "verbal", difficulty: 3,
    text: { en: "Author is to pen as sculptor is to ___", vi: "Nhà văn so với cây bút cũng như nhà điêu khắc so với ___" },
    options: [{ en: "statue", vi: "bức tượng" }, { en: "stone", vi: "khối đá" }, { en: "chisel", vi: "cái đục" }, { en: "museum", vi: "bảo tàng" }],
    answer: 2,
    explain: { en: "The relationship is worker : primary tool — a sculptor's tool is the chisel (the statue is the product, the stone the material).", vi: "Quan hệ là người làm nghề : công cụ chính — công cụ của nhà điêu khắc là cái đục (bức tượng là sản phẩm, khối đá là vật liệu)." } },
  { id: "vr08", domain: "verbal", difficulty: 3,
    text: { en: "Every poet is a dreamer. No dreamer is practical. Therefore:", vi: "Mọi nhà thơ đều là người mơ mộng. Không người mơ mộng nào thực dụng. Vậy:" },
    options: [{ en: "No poet is practical", vi: "Không nhà thơ nào thực dụng" }, { en: "Some poets are practical", vi: "Một số nhà thơ thực dụng" }, { en: "All practical people are poets", vi: "Mọi người thực dụng đều là nhà thơ" }, { en: "Nothing can be concluded", vi: "Không thể kết luận gì" }],
    answer: 0,
    explain: { en: "All poets fall inside 'dreamers', and 'dreamers' excludes 'practical' — so no poet can be practical.", vi: "Mọi nhà thơ nằm trong nhóm 'người mơ mộng', và nhóm này loại trừ 'thực dụng' — nên không nhà thơ nào thực dụng." } },

  // ---- NUMERICAL REASONING --------------------------------------------------
  { id: "nu01", domain: "numerical", difficulty: 1,
    text: { en: "What number comes next: 2, 4, 6, 8, …?", vi: "Số tiếp theo là gì: 2, 4, 6, 8, …?" },
    options: ["9", "10", "12", "16"],
    answer: 1,
    explain: { en: "The series increases by 2 each step.", vi: "Dãy số tăng thêm 2 mỗi bước." } },
  { id: "nu02", domain: "numerical", difficulty: 1,
    text: { en: "15 is what percent of 60?", vi: "15 bằng bao nhiêu phần trăm của 60?" },
    options: ["15%", "20%", "25%", "40%"],
    answer: 2,
    explain: { en: "15 ÷ 60 = 0.25 = 25%.", vi: "15 ÷ 60 = 0,25 = 25%." } },
  { id: "nu03", domain: "numerical", difficulty: 2,
    text: { en: "What number comes next: 3, 6, 12, 24, …?", vi: "Số tiếp theo là gì: 3, 6, 12, 24, …?" },
    options: ["30", "36", "48", "60"],
    answer: 2,
    explain: { en: "Each number is double the previous one.", vi: "Mỗi số gấp đôi số trước nó." } },
  { id: "nu04", domain: "numerical", difficulty: 2,
    text: { en: "A shirt costs $40 after a 20% discount. What was the original price?", vi: "Một chiếc áo giá 40$ sau khi giảm 20%. Giá gốc là bao nhiêu?" },
    options: ["$44", "$48", "$50", "$60"],
    answer: 2,
    explain: { en: "$40 is 80% of the original price: 40 ÷ 0.8 = $50.", vi: "40$ là 80% giá gốc: 40 ÷ 0,8 = 50$." } },
  { id: "nu05", domain: "numerical", difficulty: 2,
    text: { en: "What number comes next: 1, 1, 2, 3, 5, 8, …?", vi: "Số tiếp theo là gì: 1, 1, 2, 3, 5, 8, …?" },
    options: ["11", "12", "13", "16"],
    answer: 2,
    explain: { en: "Each number is the sum of the two before it (Fibonacci): 5 + 8 = 13.", vi: "Mỗi số là tổng của hai số liền trước (dãy Fibonacci): 5 + 8 = 13." } },
  { id: "nu06", domain: "numerical", difficulty: 3,
    text: { en: "3 workers build a wall in 12 days. At the same rate, how long would 9 workers take?", vi: "3 công nhân xây một bức tường trong 12 ngày. Với cùng năng suất, 9 công nhân sẽ mất bao lâu?" },
    options: [{ en: "3 days", vi: "3 ngày" }, { en: "4 days", vi: "4 ngày" }, { en: "6 days", vi: "6 ngày" }, { en: "36 days", vi: "36 ngày" }],
    answer: 1,
    explain: { en: "Triple the workers → one third the time: 12 ÷ 3 = 4 days.", vi: "Gấp ba số công nhân → thời gian còn một phần ba: 12 ÷ 3 = 4 ngày." } },
  { id: "nu07", domain: "numerical", difficulty: 3,
    text: { en: "What number comes next: 2, 3, 5, 9, 17, …?", vi: "Số tiếp theo là gì: 2, 3, 5, 9, 17, …?" },
    options: ["25", "31", "33", "34"],
    answer: 2,
    explain: { en: "The differences double: +1, +2, +4, +8, so next is +16 → 33.", vi: "Hiệu số nhân đôi: +1, +2, +4, +8, nên tiếp theo là +16 → 33." } },
  { id: "nu08", domain: "numerical", difficulty: 3,
    text: { en: "The average of five numbers is 20. Four of them are 15, 18, 22, and 25. What is the fifth?", vi: "Trung bình của năm số là 20. Bốn số trong đó là 15, 18, 22 và 25. Số thứ năm là bao nhiêu?" },
    options: ["18", "20", "22", "25"],
    answer: 1,
    explain: { en: "Total must be 5 × 20 = 100; the four given sum to 80, so the fifth is 20.", vi: "Tổng phải là 5 × 20 = 100; bốn số đã cho có tổng 80, nên số thứ năm là 20." } },

  // ---- LOGICAL / ABSTRACT REASONING ----------------------------------------
  { id: "lg01", domain: "logical", difficulty: 1,
    text: { en: "What comes next in the pattern: ○ ● ○ ● ○ …?", vi: "Hình tiếp theo trong chuỗi: ○ ● ○ ● ○ …?" },
    options: ["●", "○", "◐", "■"],
    answer: 0,
    explain: { en: "The pattern alternates: white, black, white, black…", vi: "Chuỗi luân phiên: trắng, đen, trắng, đen…" } },
  { id: "lg02", domain: "logical", difficulty: 1,
    text: { en: "All roses are flowers. Some flowers fade quickly. Therefore:", vi: "Mọi hoa hồng đều là hoa. Một số loài hoa tàn nhanh. Vậy:" },
    options: [{ en: "All roses fade quickly", vi: "Mọi hoa hồng đều tàn nhanh" }, { en: "Some roses fade quickly", vi: "Một số hoa hồng tàn nhanh" }, { en: "Roses never fade", vi: "Hoa hồng không bao giờ tàn" }, { en: "It cannot be determined", vi: "Không thể xác định được" }],
    answer: 3,
    explain: { en: "The quick-fading flowers might not include any roses — the premises don't say.", vi: "Những loài hoa tàn nhanh có thể không bao gồm hoa hồng nào — các tiền đề không cho biết điều đó." } },
  { id: "lg03", domain: "logical", difficulty: 2,
    text: { en: "What comes next: ▲ ▲ ● ▲ ▲ ● ▲ …?", vi: "Hình tiếp theo: ▲ ▲ ● ▲ ▲ ● ▲ …?" },
    options: ["●", "▲", "■", "○"],
    answer: 1,
    explain: { en: "The repeating block is ▲▲● — after the 7th symbol (▲) comes the second ▲ of the block.", vi: "Khối lặp lại là ▲▲● — sau ký hiệu thứ 7 (▲) là ▲ thứ hai của khối." } },
  { id: "lg04", domain: "logical", difficulty: 2,
    text: { en: "What comes next: AZ, BY, CX, …?", vi: "Cặp tiếp theo: AZ, BY, CX, …?" },
    options: ["DE", "DW", "EW", "DV"],
    answer: 1,
    explain: { en: "First letters go forward (A, B, C, D) while second letters go backward (Z, Y, X, W).", vi: "Chữ cái đầu tiến tới (A, B, C, D) trong khi chữ cái sau lùi lại (Z, Y, X, W)." } },
  { id: "lg05", domain: "logical", difficulty: 2,
    text: { en: "If all Blips are Blops, and no Blops are Blurs, then:", vi: "Nếu mọi Blip đều là Blop, và không Blop nào là Blur, thì:" },
    options: [{ en: "No Blips are Blurs", vi: "Không Blip nào là Blur" }, { en: "Some Blips are Blurs", vi: "Một số Blip là Blur" }, { en: "All Blurs are Blips", vi: "Mọi Blur đều là Blip" }, { en: "It cannot be determined", vi: "Không thể xác định được" }],
    answer: 0,
    explain: { en: "Blips sit entirely inside Blops, and Blops exclude Blurs — so Blips exclude Blurs too.", vi: "Blip nằm hoàn toàn trong Blop, và Blop loại trừ Blur — nên Blip cũng loại trừ Blur." } },
  { id: "lg06", domain: "logical", difficulty: 3,
    text: { en: "What letter comes next: J, F, M, A, M, J, J, A, S, O, N, …?", vi: "Chữ cái tiếp theo: J, F, M, A, M, J, J, A, S, O, N, …? (gợi ý: theo tiếng Anh)" },
    options: ["D", "J", "E", "M"],
    answer: 0,
    explain: { en: "They are the initials of the months: January … November, so December → D.", vi: "Đó là chữ cái đầu của các tháng trong tiếng Anh: January … November, nên December → D." } },
  { id: "lg07", domain: "logical", difficulty: 3,
    text: { en: "Complete the grid — Row 1: 1 2 3 · Row 2: 2 4 6 · Row 3: 3 6 ?", vi: "Hoàn thành bảng — Hàng 1: 1 2 3 · Hàng 2: 2 4 6 · Hàng 3: 3 6 ?" },
    options: ["7", "8", "9", "12"],
    answer: 2,
    explain: { en: "Each cell is row number × column number: 3 × 3 = 9.", vi: "Mỗi ô bằng số hàng × số cột: 3 × 3 = 9." } },
  { id: "lg08", domain: "logical", difficulty: 3,
    text: { en: "Anna is taller than Bea. Bea is taller than Cam. Dana is shorter than Cam. Who is second tallest?", vi: "Anna cao hơn Bea. Bea cao hơn Cam. Dana thấp hơn Cam. Ai cao thứ hai?" },
    options: ["Anna", "Bea", "Cam", "Dana"],
    answer: 1,
    explain: { en: "Order from tallest: Anna > Bea > Cam > Dana — Bea is second.", vi: "Thứ tự từ cao nhất: Anna > Bea > Cam > Dana — Bea đứng thứ hai." } },

  // ---- SPATIAL REASONING ------------------------------------------------------
  { id: "sa01", domain: "spatial", difficulty: 1,
    text: { en: "If you rotate the lowercase letter 'b' by 180°, which letter does it become?", vi: "Nếu xoay chữ thường 'b' 180°, nó trở thành chữ nào?" },
    options: ["d", "p", "q", "b"],
    answer: 2,
    explain: { en: "Rotating 'b' a half-turn flips it both vertically and horizontally, giving 'q'.", vi: "Xoay 'b' nửa vòng lật nó theo cả chiều dọc lẫn chiều ngang, thành 'q'." } },
  { id: "sa02", domain: "spatial", difficulty: 1,
    text: { en: "A clock shows exactly 3:00. What is the angle between the two hands?", vi: "Đồng hồ chỉ đúng 3:00. Góc giữa hai kim là bao nhiêu?" },
    options: ["45°", "60°", "90°", "120°"],
    answer: 2,
    explain: { en: "At 3:00 the hands span a quarter of the dial: 360° ÷ 4 = 90°.", vi: "Lúc 3:00 hai kim cách nhau một phần tư mặt đồng hồ: 360° ÷ 4 = 90°." } },
  { id: "sa03", domain: "spatial", difficulty: 2,
    text: { en: "Which of these capital letters looks the SAME in a mirror (flipped left-right)?", vi: "Chữ in hoa nào dưới đây trông GIỐNG HỆT trong gương (lật trái-phải)?" },
    options: ["A", "F", "G", "J"],
    answer: 0,
    explain: { en: "'A' is symmetric around its vertical axis, so its mirror image is unchanged.", vi: "'A' đối xứng qua trục dọc, nên ảnh trong gương của nó không đổi." } },
  { id: "sa04", domain: "spatial", difficulty: 2,
    text: { en: "How many edges does a cube have?", vi: "Một hình lập phương có bao nhiêu cạnh?" },
    options: ["8", "10", "12", "16"],
    answer: 2,
    explain: { en: "A cube has 12 edges: 4 on top, 4 on the bottom, and 4 vertical.", vi: "Hình lập phương có 12 cạnh: 4 ở mặt trên, 4 ở mặt dưới, và 4 cạnh đứng." } },
  { id: "sa05", domain: "spatial", difficulty: 2,
    text: { en: "Fold a square sheet of paper in half, then in half again. Punch ONE hole through all layers and unfold. How many holes?", vi: "Gấp đôi một tờ giấy vuông, rồi gấp đôi lần nữa. Đục MỘT lỗ xuyên qua tất cả các lớp rồi mở ra. Có bao nhiêu lỗ?" },
    options: ["1", "2", "4", "8"],
    answer: 2,
    explain: { en: "Two folds create 4 layers; one punch goes through all of them → 4 holes.", vi: "Hai lần gấp tạo 4 lớp giấy; một lần đục xuyên qua tất cả → 4 lỗ." } },
  { id: "sa06", domain: "spatial", difficulty: 3,
    text: { en: "You face north. You turn 90° right, then 180°, then 90° left. Which direction are you facing?", vi: "Bạn đang quay mặt về hướng bắc. Bạn quay phải 90°, rồi quay 180°, rồi quay trái 90°. Bạn đang quay mặt về hướng nào?" },
    options: [{ en: "North", vi: "Bắc" }, { en: "South", vi: "Nam" }, { en: "East", vi: "Đông" }, { en: "West", vi: "Tây" }],
    answer: 1,
    explain: { en: "North → (right 90°) East → (180°) West → (left 90°) South.", vi: "Bắc → (phải 90°) Đông → (180°) Tây → (trái 90°) Nam." } },
  { id: "sa07", domain: "spatial", difficulty: 3,
    text: { en: "On a die, 1 is opposite 6, 2 opposite 5, 3 opposite 4. If 1 faces up and 2 faces toward you, what number is on the back (facing away)?", vi: "Trên một con xúc xắc, 1 đối diện 6, 2 đối diện 5, 3 đối diện 4. Nếu mặt 1 hướng lên trên và mặt 2 hướng về phía bạn, số nào ở mặt sau (hướng ra xa)?" },
    options: ["3", "4", "5", "6"],
    answer: 2,
    explain: { en: "The face opposite the one toward you (2) is its pair: 5.", vi: "Mặt đối diện với mặt hướng về phía bạn (2) chính là cặp của nó: 5." } },
  { id: "sa08", domain: "spatial", difficulty: 3,
    text: { en: "A 3×3×3 cube of 27 small cubes is painted on the outside. How many small cubes have NO painted face?", vi: "Một khối 3×3×3 gồm 27 khối nhỏ được sơn toàn bộ mặt ngoài. Có bao nhiêu khối nhỏ KHÔNG có mặt nào bị sơn?" },
    options: ["0", "1", "3", "6"],
    answer: 1,
    explain: { en: "Only the single cube hidden at the very center touches no outside surface.", vi: "Chỉ có duy nhất khối nhỏ ẩn ở chính giữa không chạm vào bề mặt ngoài nào." } },

  // ---- WORKING MEMORY & ATTENTION -------------------------------------------
  { id: "me01", domain: "memory", difficulty: 1,
    text: { en: "Spell the word WORLD backwards in your head. What is the THIRD letter of the reversed word?", vi: "Đánh vần ngược từ WORLD trong đầu. Chữ cái THỨ BA của từ đảo ngược là gì?" },
    options: ["L", "R", "O", "D"],
    answer: 1,
    explain: { en: "WORLD reversed is D-L-R-O-W; the third letter is R.", vi: "WORLD đảo ngược là D-L-R-O-W; chữ cái thứ ba là R." } },
  { id: "me02", domain: "memory", difficulty: 1,
    text: { en: "Count the letter 'e' in this sentence: \"The elephant entered the tent early.\"", vi: "Đếm chữ cái 'e' trong câu tiếng Anh sau: \"The elephant entered the tent early.\"" },
    options: ["7", "8", "9", "10"],
    answer: 2,
    explain: { en: "The(1) elephant(2) entered(3) the(1) tent(1) early(1) → 9 in total.", vi: "The(1) elephant(2) entered(3) the(1) tent(1) early(1) → tổng cộng 9." } },
  { id: "me03", domain: "memory", difficulty: 2,
    text: { en: "Take the number 47, reverse its digits, then add 10. What is the result?", vi: "Lấy số 47, đảo ngược các chữ số, rồi cộng 10. Kết quả là bao nhiêu?" },
    options: ["57", "84", "74", "94"],
    answer: 1,
    explain: { en: "47 reversed is 74; 74 + 10 = 84.", vi: "47 đảo ngược là 74; 74 + 10 = 84." } },
  { id: "me04", domain: "memory", difficulty: 2,
    text: { en: "Read once, then answer from memory: 8, 3, 9, 1, 5. What is the sum of the FIRST and LAST numbers?", vi: "Đọc một lần, rồi trả lời từ trí nhớ: 8, 3, 9, 1, 5. Tổng của số ĐẦU TIÊN và số CUỐI CÙNG là bao nhiêu?" },
    options: ["11", "12", "13", "14"],
    answer: 2,
    explain: { en: "First is 8, last is 5: 8 + 5 = 13.", vi: "Số đầu là 8, số cuối là 5: 8 + 5 = 13." } },
  { id: "me05", domain: "memory", difficulty: 2,
    text: { en: "If yesterday was two days after Monday, what day is TOMORROW?", vi: "Nếu hôm qua là hai ngày sau thứ Hai, thì NGÀY MAI là thứ mấy?" },
    options: [{ en: "Thursday", vi: "Thứ Năm" }, { en: "Friday", vi: "Thứ Sáu" }, { en: "Saturday", vi: "Thứ Bảy" }, { en: "Wednesday", vi: "Thứ Tư" }],
    answer: 1,
    explain: { en: "Two days after Monday is Wednesday (yesterday) → today is Thursday → tomorrow is Friday.", vi: "Hai ngày sau thứ Hai là thứ Tư (hôm qua) → hôm nay là thứ Năm → ngày mai là thứ Sáu." } },
  { id: "me06", domain: "memory", difficulty: 3,
    text: { en: "Mentally reverse the sequence 2, 7, 4, 9. What is the SECOND number of the reversed sequence?", vi: "Đảo ngược dãy 2, 7, 4, 9 trong đầu. Số THỨ HAI của dãy đảo ngược là gì?" },
    options: ["9", "4", "7", "2"],
    answer: 1,
    explain: { en: "Reversed: 9, 4, 7, 2 — the second number is 4.", vi: "Đảo ngược: 9, 4, 7, 2 — số thứ hai là 4." } },
  { id: "me07", domain: "memory", difficulty: 3,
    text: { en: "Start with 100 and subtract 7 three times in a row. What number do you reach?", vi: "Bắt đầu từ 100 và trừ 7 ba lần liên tiếp. Bạn được số nào?" },
    options: ["76", "79", "83", "86"],
    answer: 1,
    explain: { en: "100 → 93 → 86 → 79.", vi: "100 → 93 → 86 → 79." } },
  { id: "me08", domain: "memory", difficulty: 3,
    text: { en: "In the English alphabet, what letter comes THREE letters before the letter that immediately follows M?", vi: "Trong bảng chữ cái tiếng Anh, chữ cái nào đứng TRƯỚC ba vị trí so với chữ cái liền sau M?" },
    options: ["J", "K", "L", "N"],
    answer: 1,
    explain: { en: "The letter after M is N; three before N is K (K, L, M, N).", vi: "Chữ cái sau M là N; ba vị trí trước N là K (K, L, M, N)." } },
];

/* ---- Quick-version subset: items 01/03/05/07 of each domain (20 items,
   1 easy + 2 medium + 1 hard per domain — keep this mix if edited) ---- */
const IQ_CORE_SUFFIXES = ["01", "03", "05", "07"];
IQ_QUESTIONS.forEach((q) => {
  q.core = IQ_CORE_SUFFIXES.includes(q.id.slice(-2));
});
const IQ_QUESTIONS_CORE = IQ_QUESTIONS.filter((q) => q.core);
